name: 🐛 Bug Report
description: Report a bug with a Cloudflare node
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: dropdown
    id: node
    attributes:
      label: Which node is affected?
      description: Select the Cloudflare node where you encountered the issue
      options:
        - Cloudflare DNS
        - Cloudflare Workers
        - Cloudflare Zones
        - Cloudflare Zero Trust
        - Cloudflare Security (Firewall)
        - Cloudflare SSL
        - Cloudflare R2
        - Cloudflare KV
        - Cloudflare D1
        - Cloudflare Pages
        - Cloudflare Stream
        - Cloudflare Images
        - Cloudflare Load Balancer
        - Cloudflare Email Routing
        - Cloudflare Tunnels
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: resource
    attributes:
      label: Which resource/operation?
      description: Select the resource type you were using
      options:
        - DNS Record
        - Zone Settings
        - Worker Script
        - KV Namespace
        - R2 Bucket
        - D1 Database
        - Access Application
        - Tunnel
        - Firewall Rule
        - Certificate
        - Cache
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: operation
    attributes:
      label: What operation were you performing?
      options:
        - Create
        - Get
        - Get Many / List
        - Update
        - Delete
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
      placeholder: |
        When I try to create a DNS record, the node fails with...
        I expected the record to be created but instead...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message
      description: Paste any error messages you received
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Node Configuration
      description: Share your node settings (remove sensitive data)
      render: json

  - type: input
    id: n8n-version
    attributes:
      label: n8n Version
      placeholder: "1.70.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: n8n-nodes-cloudflare Version
      placeholder: "0.1.0-beta.0"
    validations:
      required: true
